### ISSUE TITLE
empty `Mixin.g.cs` file

### ISSUE THREAD

**Issue by Enteleform** [LokiMidgard/PartialMixins#1]
Just tried using the `README.md` example with the latest version of Visual Studio & Xamarin.

The `Mixin.g.cs` file is empty, so I get the following error:

```
Error CS1061
'MainPage.BusinessObject' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'MainPage.BusinessObject' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by LokiMidgard** [comment]
I currently have no Xamarin installed, but do you know what project format Xamarin uses?

This project was created before the new Project format, maybe the used librarys to generate the type info of it can't handle it. It uses 1.2.1 of `Microsoft.CodeAnalysis.CSharp`. Latest stable is 2.6.

If this is the Problem, I hope I can fix it between the holiday.

By the way. It still should work on normal .Net Framework Projects. Just Tested it with new console Application. If this does not work the error could be something else.

**Comment by Enteleform** [comment]
New to VS, not really sure what info you're asking about.

Here are the [**.sln**](https://gist.github.com/Enteleform/718554067dc3531595c621adf347f3d7#file-sln) & [**.csproj**](https://gist.github.com/Enteleform/718554067dc3531595c621adf347f3d7#file-csproj) files.

**Comment by LokiMidgard** [comment]
I'm not 100% sure, but it doesn't look like the knew format for me.

However what my projects get after adding the nuget package are following lines:
```xml
    <Error Condition="!Exists('..\packages\PartialMixin.0.8.2.35720\build\PartialMixin.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\PartialMixin.0.8.2.35720\build\PartialMixin.props'))" />
    <Error Condition="!Exists('..\packages\PartialMixin.0.8.2.35720\build\PartialMixin.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\PartialMixin.0.8.2.35720\build\PartialMixin.targets'))" />

...

  <Import Project="..\packages\PartialMixin.0.8.2.35720\build\PartialMixin.targets" Condition="Exists('..\packages\PartialMixin.0.8.2.35720\build\PartialMixin.targets')" />

```
And without the target file the generator should not be triggered on build.  
But it is strange that the ```Mixin.g.cs``` file was generated at all.

Can you check if VS still shows the Nuget package as installed. Maybe it was removed fore some obscure reason.

I think I can look into Xamarin  at the weekend.

**Comment by Enteleform** [comment]
The package was installed when I created the issue, but not when I posted the project files. Ended up implementing extension-type mixins in the meantime.

**Comment by LokiMidgard** [comment]
I was able to reproduce the behavior. The problem was that the Nuget package did not reference the ```Mixin.dll``` for the .Net standard project. Some problem with the nuget package definition. Untill this is fixed there are two workarounds:

-------------------------------------------------------------------------------------

 You can manually add the dll. On my pc nuget put it under ```C:\Users\[USER_NAME]\.nuget\packages\partialmixin\0.8.2.35720\tools```

---------------------------------------------------------------

Having binarys in you repo is not so nice. Another workaround would be to create a project in your solution with the name ```Mixin``` that has following class:

```c#
using System;

namespace Mixin
{
    [System.AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    public sealed class MixinAttribute : Attribute
    {

        public MixinAttribute(Type toImplement)
        {
        }


    }
}
```
Then adding a reference to this project.

-------------------------------------------------------

I would like to hear if one of this solution fixes your problems. otherwise I need to investigate further.

**Comment by LokiMidgard** [comment]
Updated Package on nuget to now support netstandard1.0.

This should now work for Xamarin projects (as long you build on windows)

**Comment by Enteleform** [comment]
Awesome, just tested it & it works perfectly.

This is a great package man, seriously makes coding in C# a lot cleaner. Just moved to Xamarin after working with Python a bunch & was kind of horrified that I might've had to use some unholy mixture of properties & getter/setter methods. Thanks for providing an alternative while Microsoft gets their shit together : )
