### ISSUE TITLE
MixinAttribute already defined?

### ISSUE THREAD

**Issue by znakeeye** [LokiMidgard/PartialMixins#15]
Using `Visual Studio 2022` (17.3.1). Any help is greatly appreciated. Aiming at creating some pull requests, but this one might need your expertise! Thanks :)

1. Create a new WPF project. Target .NET 6.
2. Add a reference to `PartialMixin 1.0.55`
3. Replace `MainWindow.xaml.cs` with the code below.

**First (minor) problem**
Visual Studio is unable to resolve the `MixinAttribute` without manually adding the namespace. Weird!

![image](https://user-images.githubusercontent.com/958469/187460869-ce2fcc7d-c50e-4198-bae6-74a96d584281.png)

**Second problem**
The compiler complains about duplicate attributes and stuff. Once you get this error, the project is forever crippled! No matter what you do, it will produce this compilation error. Amazing stuff... Maybe the guid seen in the `VSGeneratedDocuments` folder has something to do with this?

![image](https://user-images.githubusercontent.com/958469/187461250-73502b72-c2ee-40d5-8adc-ac4ddc1519bd.png)

```
Build started...
1>------ Build started: Project: MixinError, Configuration: Debug Any CPU ------
1>C:\Foo\PartialMixins\PartialMixins.PartialMixin\MixinAttribute.cs(5,25,5,39): error CS0101: The namespace 'Mixin' already contains a definition for 'MixinAttribute'
1>C:\Foo\MainWindow.xaml.cs(14,2,14,20): error CS0121: The call is ambiguous between the following methods or properties: 'MixinAttribute.MixinAttribute(Type)' and 'MixinAttribute.MixinAttribute(Type)'
1>C:\Foo\MainWindow.xaml.cs(15,2,15,20): error CS0121: The call is ambiguous between the following methods or properties: 'MixinAttribute.MixinAttribute(Type)' and 'MixinAttribute.MixinAttribute(Type)'
1>C:\Foo\PartialMixins\PartialMixins.PartialMixin\MixinAttribute.cs(4,6,4,27): error CS0579: Duplicate 'System.AttributeUsage' attribute
1>C:\Foo\PartialMixins\PartialMixins.PartialMixin\MixinAttribute.cs(7,16,7,30): error CS0111: Type 'MixinAttribute' already defines a member called 'MixinAttribute' with the same parameter types
1>Done building project "MixinError_znfwmrwh_wpftmp.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**MainWindow.xaml.cs**
```c#
using System.Windows;
using Mixin;

namespace MixinError;

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
    }
}

// NOTE: Two attributes! Is this somehow related to the compilation error?
[Mixin(typeof(Bar))]
[Mixin(typeof(Baz))]
public partial class Foo
{
}

class Bar
{
    public string TheBar { get; set; }
}

class Baz
{
    public string TheBaz { get; set; }
}
```

**Comment by LokiMidgard** [comment]
The two Attributes should not be a problem. The generator should only emit one Mixin attirbute ever.

Just to be sure, the screenshot does highligt the generate class option. You haven't used this and generated an additional class.
It may be that in the beginning no code is emmited and no Attribute exists. It will be emitted on frist run, and then the corresponding option to import the namespace should exists. So the error (Class not found) should vanisch after the firts build.

If that is not the case maybe share the sample. I wasnt able to reproduce it yet…
And there are not that many steps I could screw up…

**Comment by znakeeye** [comment]
Thanks for your quick response. No, I did not generate a class. In fact, it is 100% reproducible in any new `WPF` project.

Here's a sample project: [SimpleMixinTest.zip](https://github.com/LokiMidgard/PartialMixins/files/9455022/SimpleMixinTest.zip)
Rebuild, boom!

I'm wondering if the `WPF` project type itself suffers from some really weird analyzer issue. I.e. some conflict with its XAML source generator?

**Comment by znakeeye** [comment]
I can confirm that the error only occurs when a `.xaml` file is included in the project.

**Comment by znakeeye** [comment]
https://github.com/dotnet/wpf/issues/6792

Adding this in the project file solves the problem!!

```xaml
<Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
    <!-- Work around https://github.com/dotnet/wpf/issues/6792 -->
    <ItemGroup>
         <FilteredAnalyzer Include="@(Analyzer->Distinct())" />
             <Analyzer Remove="@(Analyzer)" />
             <Analyzer Include="@(FilteredAnalyzer)" />
    </ItemGroup>
</Target>
```

**Comment by LokiMidgard** [comment]
Ah Thank you, I did not have the affectede DotNet 6 version…
