### ISSUE TITLE
Port generator to netstandard

### ISSUE THREAD

**Issue by LokiMidgard** [LokiMidgard/PartialMixins#2]
I would like to bring this to netstandard, but currently there is no support for ```MSBuildWorkspace```.

Hope this can happen if dotnet/roslyn#23011 will be closed.

**Comment by aniongithub** [comment]
I have a pull request that does this for your library! :)

https://github.com/LokiMidgard/PartialMixins/pull/3

**Comment by LokiMidgard** [comment]
I was finally able to merge your request. Thank you :)

**Comment by LokiMidgard** [comment]
Unfortunately it no longer working. Buildalizer that is now used in .NetCore will trigger an build that triggers the tool again.

I opened an [issue](https://github.com/daveaglick/Buildalyzer/issues/109) to inquiry if there is a way to suppress this.

**Comment by LokiMidgard** [comment]
It seems to finally work again :)

But the compilation is pretty slow. The initial generation of the project takes the most time.

The problem here can be that auto completion will no longer reflect the changes before the build was actually triggered. This will also hinder other tools that riley on coreCompile, like XAML :(
