### ISSUE TITLE
Use Roslyn Generator framework

### ISSUE THREAD

**Issue by LokiMidgard** [LokiMidgard/PartialMixins#5]
We currently run in (before) CoreCompile. But for that build step we are actually to slow it seems.

We need to increase the runtime of this tool significant. (ms instead of seconds)

**Comment by LokiMidgard** [comment]
We got faster (currently develop) but I would like to get even faster.

**Comment by daiplusplus** [comment]
This project could be modified to work within the Code-Generation features now built-in to Roslyn - this would solve a number of problems:

- Simpler build process (fewer external dependencies)
- Cross-platform support (no need to invoke command-line tools, and work from the `msbuild` and `dotnet build` command-line, not just from within Visual Studio.

https://docs.microsoft.com/en-us/archive/msdn-magazine/2017/may/net-core-cross-platform-code-generation-with-roslyn-and-net-core

**Comment by LokiMidgard** [comment]
Your right, I habe some projects that need that treatment.
And this is priority no. 1 (for this project). I try to look at it this evening, but it could also be the next days or months since its just a hobby.
